name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release_needed: ${{ steps.check_tag.outputs.release_needed }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: make build

    - name: set output
      id: check_tag
      run: |
        git fetch --tags
        git describe --tags --exact-match --match 'v[0-9]*.[0-9]*.[0-9]**' \
        && echo "release_needed=1" >> $GITHUB_OUTPUT \
        || true

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test with curl
      run: make test

  scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: do a parallel scan
      run: make scan

  release:
    runs-on: ubuntu-latest
    needs:
      - test
      - scan
    if: ${{ needs.check_tag.outputs.release_needed == 'true' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: release
      run: make release
