name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: make build

    - name: push Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_CLASSIC_REPO_WRITE_PACKAGES }}
        IMAGE: 'reverse'
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}${IMAGE}
        docker tag ${IMAGE}:latest ${GHCR_IMAGE}:latest
        docker push ${GHCR_IMAGE}:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      release_needed: ${{ steps.check_tag.outputs.release_needed }}
      github_tag: ${{ steps.check_tag.outputs.github_tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: pull Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_CLASSIC_REPO_READ_PACKAGES }}
        IMAGE: 'reverse'
      run: |
        echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}${IMAGE}
        docker pull ${GHCR_IMAGE}:latest
        docker tag  ${GHCR_IMAGE}:latest ${IMAGE}:latest
        
    - name: Test with curl
      run: make test
      
    - name: set output
      id: check_tag
      run: |
        git fetch --tags          
        git describe --tags --exact-match --match 'v[0-9]*.[0-9]*.[0-9]*' \
        && ( echo "release_needed=true" >> $GITHUB_OUTPUT \
             && echo "github_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT ) \
        || true

  scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: do a parallel scan
      run: make scan

  release:
    runs-on: ubuntu-latest
    needs:
      - test
      - scan
    if: ${{ needs.test.outputs.release_needed == 'true' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: release
      run: make release

    - name: echo version
      run: echo ${{ needs.test.outputs.github_tag }}
