name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      scan_needed: ${{ steps.check_scan.outputs.scan_needed }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: make build

    - name: set output
      id: check_scan
      run: run: echo "scan_needed=1" >> $GITHUB_OUTPUT


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test with curl
      run: make test

  scan:
    runs-on: ubuntu-latest
    needs: build

    if: ${{ needs.check_scan.outputs.scan_needed == '1' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: do a parallel scan
      run: make scan

  release:
    runs-on: ubuntu-latest
    needs:
      - test
      - scan
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: release
      run: make release
