name: test hello

on:
  workflow_dispatch:

jobs:
  test-hello:
    runs-on: ubuntu-latest

    steps:
    - name: test hello foobar
      uses: dennisyau1885/hello@v1
      with:
        person: foobar

    - name: test Hello foobaz
      uses: dennisyau1885/hello@v2
      with:
        person: foobaz
